import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./component/Header";
import Footer from "./component/Footer";
// import { ThemeProvider } from "next-themes";
import ScrollProgress from "./component/ScrollProgess";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "personal portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen mx-auto max-w-7xl shadow-3xl bg-white text-black dark:bg-[#0f0f0f] dark:text-white px-4 pb-16 bg-white dark:bg-black`}
      >
        {/* <ThemeProvider attribute="class" defaultTheme="system" enableSystem> */}
        <Header />
        <ScrollProgress />
        {children}
        <Footer />
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
